// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5wHfUSouare7VFcIz-6Zt_p-R9l0FNM',
    appId: '1:331953864757:web:ba525da56d4619131bf17c',
    messagingSenderId: '331953864757',
    projectId: 'todo-app21f',
    authDomain: 'todo-app21f.firebaseapp.com',
    storageBucket: 'todo-app21f.appspot.com',
    measurementId: 'G-GFF08GFTS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpca86nYXwustiWgPfdua0QvksgVc1Y8Y',
    appId: '1:331953864757:android:623d9da0d654bece1bf17c',
    messagingSenderId: '331953864757',
    projectId: 'todo-app21f',
    storageBucket: 'todo-app21f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIt_FAJ1CNIkqwlxe_yLlC94Tf0v5L2aM',
    appId: '1:331953864757:ios:2918a8273e388f051bf17c',
    messagingSenderId: '331953864757',
    projectId: 'todo-app21f',
    storageBucket: 'todo-app21f.appspot.com',
    iosBundleId: 'com.example.todoAppUsingfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_5wHfUSouare7VFcIz-6Zt_p-R9l0FNM',
    appId: '1:331953864757:web:142e62d908f2e8911bf17c',
    messagingSenderId: '331953864757',
    projectId: 'todo-app21f',
    authDomain: 'todo-app21f.firebaseapp.com',
    storageBucket: 'todo-app21f.appspot.com',
    measurementId: 'G-PV8JZNLLEH',
  );
}
